name: Backend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      JWT_SECRET: test-secret-key-for-ci
      MONGO_URI: mongodb://localhost:27017/test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: cd server && pnpm install
      - run: cd server && pnpm run lint
      - run: cd server && pnpm test 